In [116]:
import pandas as pd

In [117]:
person = {
 "first" : "corey",
 "last" : "schafer",
"email" :"coreyschafer@email.com"
}


people = {
 "first" : ["corey"],
 "last" : ["schafer"],
"email" : ["coreyschafer@email.com"]
}

people = {
 "first" : ['corey', 'Jane', 'John'],
 "last" : ['schafer', 'Doe', 'Doe'],
"email" : ['coreyschafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [118]:
people['email']

['coreyschafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']

In [119]:
dff = pd.DataFrame(people)

In [120]:
dff['email']

0    coreyschafer@email.com
1         JaneDoe@email.com
2         JohnDoe@email.com
Name: email, dtype: object

In [121]:
dff.email

0    coreyschafer@email.com
1         JaneDoe@email.com
2         JohnDoe@email.com
Name: email, dtype: object

In [122]:
dff

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [123]:
dff[['last','email']]

      last                   email
0  schafer  coreyschafer@email.com
1      Doe       JaneDoe@email.com
2      Doe       JohnDoe@email.com

In [124]:
dff.columns

Index(['first', 'last', 'email'], dtype='object')

In [125]:
dff.iloc[0]

first                     corey
last                    schafer
email    coreyschafer@email.com
Name: 0, dtype: object

In [126]:
dff.iloc[0,1]

'schafer'

In [127]:
dff.shape

(3, 3)

In [128]:
dff.iloc[[0,1,2],[0,1,2]]

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [129]:
dff.iloc[0:3,0:3]

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [130]:
dff.loc[[0,1,2],['email', 'last']]

                    email     last
0  coreyschafer@email.com  schafer
1       JaneDoe@email.com      Doe
2       JohnDoe@email.com      Doe

In [131]:
dff.loc[0]

first                     corey
last                    schafer
email    coreyschafer@email.com
Name: 0, dtype: object

In [132]:
dff.loc[0:2]

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [133]:
dff.loc[0:2,'first':'last']

   first     last
0  corey  schafer
1   Jane      Doe
2   John      Doe

In [134]:
dff.iloc[0]

first                     corey
last                    schafer
email    coreyschafer@email.com
Name: 0, dtype: object

In [135]:
dff.iloc[0:3, 0:3]

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [136]:
dff.columns

Index(['first', 'last', 'email'], dtype='object')

In [137]:
# INDEXES [How to set Index, Reset, Use of Indexes]

In [138]:
dff

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [139]:
dff['email']

0    coreyschafer@email.com
1         JaneDoe@email.com
2         JohnDoe@email.com
Name: email, dtype: object

In [140]:
#Now I want to set the email as the index, so we can have some meaningful name to the index value
dff.set_index('email',inplace=True)

In [141]:
dff

                        first     last
email
coreyschafer@email.com  corey  schafer
JaneDoe@email.com        Jane      Doe
JohnDoe@email.com        John      Doe

In [142]:
dff.index

Index(['coreyschafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com'], dtype='object', name='email')

In [143]:
dff.loc['coreyschafer@email.com']

first      corey
last     schafer
Name: coreyschafer@email.com, dtype: object

In [144]:
dff.loc['coreyschafer@email.com':'JohnDoe@email.com']

                        first     last
email
coreyschafer@email.com  corey  schafer
JaneDoe@email.com        Jane      Doe
JohnDoe@email.com        John      Doe

In [145]:
dff['last']

email
coreyschafer@email.com    schafer
JaneDoe@email.com             Doe
JohnDoe@email.com             Doe
Name: last, dtype: object

In [146]:
(dff['last'] == 'Doe') & (dff['first'] == 'Jane')

email
coreyschafer@email.com    False
JaneDoe@email.com          True
JohnDoe@email.com         False
dtype: bool

In [147]:
dff[(dff['last'] == 'Doe') & (dff['first'] == 'Jane')]

                  first last
email
JaneDoe@email.com  Jane  Doe

In [148]:
filt = (dff['last'] == 'Doe') & (dff['first'] == 'Jane')
dff.loc[filt, 'last']

email
JaneDoe@email.com    Doe
Name: last, dtype: object

In [150]:
dff = dff.reset_index()

In [151]:
filt = (dff['last'] == 'Doe') & (dff['first'] == 'Jane')
dff.loc[filt, 'email']

1    JaneDoe@email.com
Name: email, dtype: object

In [154]:
filt = (dff['last'] == 'schafer') | (dff['first'] == 'John')
dff.loc[filt, 'email']

0    coreyschafer@email.com
2         JohnDoe@email.com
Name: email, dtype: object

In [155]:
dff.loc[~filt, 'email']

1    JaneDoe@email.com
Name: email, dtype: object