In [176]:
import pandas as pd

In [177]:
person = {
 "first" : "corey",
 "last" : "schafer",
"email" :"coreyschafer@email.com"
}


people = {
 "first" : ["corey"],
 "last" : ["schafer"],
"email" : ["coreyschafer@email.com"]
}

people = {
 "first" : ['corey', 'Jane', 'John'],
 "last" : ['schafer', 'Doe', 'Doe'],
"email" : ['coreyschafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [178]:
df = pd.DataFrame(people)
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [179]:
df['last']

0    schafer
1        Doe
2        Doe
Name: last, dtype: object

In [180]:
df[['last', 'first']]

      last  first
0  schafer  corey
1      Doe   Jane
2      Doe   John

In [181]:
df[['last', 'first','email']]

      last  first                   email
0  schafer  corey  coreyschafer@email.com
1      Doe   Jane       JaneDoe@email.com
2      Doe   John       JohnDoe@email.com

In [182]:
df['last']            # ✓ single column — returns a Series
df[['last']]          # ✓ single column — returns a DataFrame
df[['last', 'first']] # ✓ multiple columns — returns a DataFrame

# df['last', 'first']   # ✗ KeyError — pandas sees this as a tuple key

      last  first
0  schafer  corey
1      Doe   Jane
2      Doe   John

In [183]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [184]:
df.columns = ['first_name', 'last_name','email']

In [185]:
df

  first_name last_name                   email
0      corey   schafer  coreyschafer@email.com
1       Jane       Doe       JaneDoe@email.com
2       John       Doe       JohnDoe@email.com

In [186]:
df.rename(columns={'first_name': 'first'})

   first last_name                   email
0  corey   schafer  coreyschafer@email.com
1   Jane       Doe       JaneDoe@email.com
2   John       Doe       JohnDoe@email.com

In [187]:
df.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [188]:
df.columns = [x.upper() for x in df.columns]

In [189]:
df

  FIRST_NAME LAST_NAME                   EMAIL
0      corey   schafer  coreyschafer@email.com
1       Jane       Doe       JaneDoe@email.com
2       John       Doe       JohnDoe@email.com

In [190]:
df[['FIRST_NAME']]

  FIRST_NAME
0      corey
1       Jane
2       John

In [191]:
df.columns = df.columns.str.replace('_','-')
df

  FIRST-NAME LAST-NAME                   EMAIL
0      corey   schafer  coreyschafer@email.com
1       Jane       Doe       JaneDoe@email.com
2       John       Doe       JohnDoe@email.com

In [192]:
df.columns = df.columns.str.replace('-','_')
df

  FIRST_NAME LAST_NAME                   EMAIL
0      corey   schafer  coreyschafer@email.com
1       Jane       Doe       JaneDoe@email.com
2       John       Doe       JohnDoe@email.com

In [193]:
df.columns = [x.lower() for x in df.columns]

In [194]:
df

  first_name last_name                   email
0      corey   schafer  coreyschafer@email.com
1       Jane       Doe       JaneDoe@email.com
2       John       Doe       JohnDoe@email.com

In [195]:
df.rename(columns={'first_name':'first', 'last_name':'last'},inplace = True)

In [196]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [197]:
df.loc[2] = ['John','Smith', 'JohnSmith@email.com']

In [198]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John    Smith     JohnSmith@email.com

In [199]:
df.loc[2, ['last','email']] = ['Doe', 'JohnDoe@email.com']

In [200]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [201]:
df.loc[2, 'last'] = 'Smith'

In [202]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John    Smith       JohnDoe@email.com

In [203]:
df.at[2, 'last'] = 'Doe'

In [204]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [205]:
filt = (df['email'] == 'JohnDoe@email.com')

In [206]:
df.loc[filt,['email','last']]

               email last
2  JohnDoe@email.com  Doe

In [207]:
df.loc[filt]

  first last              email
2  John  Doe  JohnDoe@email.com

In [208]:
df.loc[filt, 'email'].str.lower()

2    johndoe@email.com
Name: email, dtype: object

In [209]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [210]:
df['email'] = df['email'].str.lower()

In [211]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       janedoe@email.com
2   John      Doe       johndoe@email.com

In [212]:
# apply, applymap, map, replace

In [ ]:
#so the apply helps use to use a method on the series or on dataframe
df['email'].apply(len)

0    22
1    17
2    17
Name: email, dtype: int64

In [214]:
def update_email(email):
    return email.upper()
def lower_email(email):
    return email.lower()

df['email'] = df['email'].apply(update_email)

In [215]:
df

   first     last                   email
0  corey  schafer  COREYSCHAFER@EMAIL.COM
1   Jane      Doe       JANEDOE@EMAIL.COM
2   John      Doe       JOHNDOE@EMAIL.COM

In [216]:
df['email'] = df['email'].apply(lower_email)
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       janedoe@email.com
2   John      Doe       johndoe@email.com

In [217]:
df.apply(len)

first    3
last     3
email    3
dtype: int64

In [218]:
df.applymap(len)

C:\Users\vegeshsai_boppana\AppData\Local\Temp\ipykernel_15140\1485728669.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   first  last  email
0      5     7     22
1      4     3     17
2      4     3     17

In [219]:
df.map(len)

   first  last  email
0      5     7     22
1      4     3     17
2      4     3     17

In [220]:
df = df.map(str.upper)

In [221]:
df = df.map(str.lower)

In [222]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   jane      doe       janedoe@email.com
2   john      doe       johndoe@email.com

In [223]:
df['first'] = df['first'].map({'corey': 'Chris', 'jane': 'Jack'})

In [224]:
df['first']

0    Chris
1     Jack
2      NaN
Name: first, dtype: object

In [232]:
df['first'] = df['first'].fillna('john')

In [233]:
df['first']

0    Chris
1     Jack
2     john
Name: first, dtype: object

In [235]:
df['first'] = df['first'].replace({'Chris': 'Corey', 'Jack':'Jane'})

In [236]:
df['first']

0    Corey
1     Jane
2     john
Name: first, dtype: object

In [237]:
df

   first     last                   email
0  Corey  schafer  coreyschafer@email.com
1   Jane      doe       janedoe@email.com
2   john      doe       johndoe@email.com