In [1]:
import pandas as pd

In [2]:
person = {
 "first" : "corey",
 "last" : "schafer",
"email" :"coreyschafer@email.com"
}


people = {
 "first" : ["corey"],
 "last" : ["schafer"],
"email" : ["coreyschafer@email.com"]
}

people = {
 "first" : ['corey', 'Jane', 'John'],
 "last" : ['schafer', 'Doe', 'Doe'],
"email" : ['coreyschafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [4]:
df = pd.DataFrame(people)

In [5]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [6]:
df.email

0    coreyschafer@email.com
1         JaneDoe@email.com
2         JohnDoe@email.com
Name: email, dtype: object

In [7]:
df['fullname'] = df['first']+df['last']

In [8]:
df

   first     last                   email      fullname
0  corey  schafer  coreyschafer@email.com  coreyschafer
1   Jane      Doe       JaneDoe@email.com       JaneDoe
2   John      Doe       JohnDoe@email.com       JohnDoe

In [11]:
df[['email','last']]

                    email     last
0  coreyschafer@email.com  schafer
1       JaneDoe@email.com      Doe
2       JohnDoe@email.com      Doe

In [12]:
type(df['email'])

pandas.core.series.Series

In [13]:
type(df[['email','last']])

pandas.core.frame.DataFrame

In [14]:
df.columns

Index(['first', 'last', 'email', 'fullname'], dtype='object')

In [15]:
df.iloc[0]

first                        corey
last                       schafer
email       coreyschafer@email.com
fullname              coreyschafer
Name: 0, dtype: object

In [19]:
df.loc[0]

first                        corey
last                       schafer
email       coreyschafer@email.com
fullname              coreyschafer
Name: 0, dtype: object

In [20]:
df.iloc[[0,1]]

   first     last                   email      fullname
0  corey  schafer  coreyschafer@email.com  coreyschafer
1   Jane      Doe       JaneDoe@email.com       JaneDoe

In [22]:
df.iloc[[0,1],3]

0    coreyschafer
1         JaneDoe
Name: fullname, dtype: object

In [24]:
df.loc[[0,1],'email']

0    coreyschafer@email.com
1         JaneDoe@email.com
Name: email, dtype: object

In [25]:
df.loc[[0,1],['email','last']]

                    email     last
0  coreyschafer@email.com  schafer
1       JaneDoe@email.com      Doe

In [26]:
df.loc[[0,2],['email','last']]

                    email     last
0  coreyschafer@email.com  schafer
2       JohnDoe@email.com      Doe

In [27]:
df.loc[[0,2],['last','email',]]

      last                   email
0  schafer  coreyschafer@email.com
2      Doe       JohnDoe@email.com

In [ ]:
df.value_counts()

first  last     email                   fullname
Jane   Doe      JaneDoe@email.com       JaneDoe         1
John   Doe      JohnDoe@email.com       JohnDoe         1
corey  schafer  coreyschafer@email.com  coreyschafer    1
Name: count, dtype: int64

In [33]:
df.email.value_counts()

email
coreyschafer@email.com    1
JaneDoe@email.com         1
JohnDoe@email.com         1
Name: count, dtype: int64