In [1]:
import numpy as np
import pandas as pd

In [2]:
people = {
 "first" : ['corey', 'Jane', 'John'],
 "last" : ['schafer', 'Doe', 'Doe'],
"email" : ['coreyschafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [3]:
df = pd.DataFrame(people)

In [7]:
df.columns=['first_name','last_name',"fullemail"]

In [8]:
df

  first_name last_name               fullemail
0      corey   schafer  coreyschafer@email.com
1       Jane       Doe       JaneDoe@email.com
2       John       Doe       JohnDoe@email.com

In [9]:
df.columns = [x.upper() for x in df.columns]

In [10]:
df

  FIRST_NAME LAST_NAME               FULLEMAIL
0      corey   schafer  coreyschafer@email.com
1       Jane       Doe       JaneDoe@email.com
2       John       Doe       JohnDoe@email.com

In [11]:
df.columns = df.columns.str.replace('_',' ')

In [12]:
df

  FIRST NAME LAST NAME               FULLEMAIL
0      corey   schafer  coreyschafer@email.com
1       Jane       Doe       JaneDoe@email.com
2       John       Doe       JohnDoe@email.com

In [13]:
df.columns = df.columns.str.replace(' ','_')

In [14]:
df

  FIRST_NAME LAST_NAME               FULLEMAIL
0      corey   schafer  coreyschafer@email.com
1       Jane       Doe       JaneDoe@email.com
2       John       Doe       JohnDoe@email.com

In [15]:
df.columns = [x.lower() for x in df.columns]

In [16]:
df

  first_name last_name               fullemail
0      corey   schafer  coreyschafer@email.com
1       Jane       Doe       JaneDoe@email.com
2       John       Doe       JohnDoe@email.com

In [19]:
df.rename(columns={'first_name': 'first'},inplace=True)

In [20]:
df

   first last_name               fullemail
0  corey   schafer  coreyschafer@email.com
1   Jane       Doe       JaneDoe@email.com
2   John       Doe       JohnDoe@email.com

In [21]:
df.loc[2]

first                     John
last_name                  Doe
fullemail    JohnDoe@email.com
Name: 2, dtype: object

In [22]:
df.loc[2] = ['John', 'Smith', 'JohnSmith@email.com']

In [23]:
df.loc[2,['last','email']] = ['Doe','JohnDoe@email.com']

In [24]:
df

   first last_name               fullemail last              email
0  corey   schafer  coreyschafer@email.com  NaN                NaN
1   Jane       Doe       JaneDoe@email.com  NaN                NaN
2   John     Smith     JohnSmith@email.com  Doe  JohnDoe@email.com

In [27]:
df.at[2,'last'] = 'Doeee'

In [28]:
df

   first last_name               fullemail   last              email
0  corey   schafer  coreyschafer@email.com    NaN                NaN
1   Jane       Doe       JaneDoe@email.com    NaN                NaN
2   John     Smith     JohnSmith@email.com  Doeee  JohnDoe@email.com

In [31]:
df['last'].fillna('yoyo',inplace=True)

In [32]:
df

   first last_name               fullemail   last              email
0  corey   schafer  coreyschafer@email.com   yoyo                NaN
1   Jane       Doe       JaneDoe@email.com   yoyo                NaN
2   John     Smith     JohnSmith@email.com  Doeee  JohnDoe@email.com

In [34]:
filt = (df.fullemail == 'JaneDoe@email.com')

In [39]:
df.loc[filt,'last'] = ['Doe']

### df[filt,'last'] = ['Doe']  this code which is commented will not work

In [40]:
df

   first last_name               fullemail   last              email
0  corey   schafer  coreyschafer@email.com   yoyo                NaN
1   Jane       Doe       JaneDoe@email.com    Doe                NaN
2   John     Smith     JohnSmith@email.com  Doeee  JohnDoe@email.com

In [50]:
df.loc[1, 'fullemail'] = df.loc[1, 'fullemail'].lower()

In [51]:
df

   first last_name               fullemail   last              email
0  corey   schafer  coreyschafer@email.com   yoyo                NaN
1   Jane       Doe       janedoe@email.com    Doe                NaN
2   John     Smith     JohnSmith@email.com  Doeee  JohnDoe@email.com

In [ ]:
# apply, applymap, map, replace, rename

# apply works differently on the series and the dataframe, be careful with that

# applymap is depreceated use map instead

In [53]:
df.apply(len, axis = 'columns')

0    5
1    5
2    5
dtype: int64

In [54]:
df.apply(len)

first        3
last_name    3
fullemail    3
last         3
email        3
dtype: int64

In [64]:
df.loc[:, 'first':'last'].apply(pd.Series.min)

first                       Jane
last_name                    Doe
fullemail    JohnSmith@email.com
last                         Doe
dtype: object

In [68]:
df['email'].fillna('y', inplace=True)

In [69]:
df.applymap(len)

C:\Users\vegeshsai_boppana\AppData\Local\Temp\ipykernel_24216\1485728669.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   first  last_name  fullemail  last  email
0      5          7         22     4      1
1      4          3         17     3      1
2      4          5         19     5     17

In [70]:
df.map(len)

   first  last_name  fullemail  last  email
0      5          7         22     4      1
1      4          3         17     3      1
2      4          5         19     5     17

In [71]:
df['first'] = df['first'].map({'corey': 'Chris', 'jane': 'Jack'})

In [72]:
df

   first last_name               fullemail   last              email
0  Chris   schafer  coreyschafer@email.com   yoyo                  y
1    NaN       Doe       janedoe@email.com    Doe                  y
2    NaN     Smith     JohnSmith@email.com  Doeee  JohnDoe@email.com

In [81]:
df['first'].fillna(df['last_name'],inplace=True)

C:\Users\vegeshsai_boppana\AppData\Local\Temp\ipykernel_24216\603404009.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['first'].fillna(df['last_name'],inplace=True)

In [82]:
df

     first last_name               fullemail   last              email
0  schafer   schafer  coreyschafer@email.com   yoyo                  y
1      Doe       Doe       janedoe@email.com    Doe                  y
2    Smith     Smith     JohnSmith@email.com  Doeee  JohnDoe@email.com

In [86]:
df['first'].replace({'Doe':'Dog'}, inplace= True)

In [87]:
df

     first last_name               fullemail   last              email
0  schafer   schafer  coreyschafer@email.com   yoyo                  y
1      Dog       Doe       janedoe@email.com    Doe                  y
2    Smith     Smith     JohnSmith@email.com  Doeee  JohnDoe@email.com

In [88]:
df['boolean'] = 'Yes'

In [89]:
df

     first last_name               fullemail   last              email boolean
0  schafer   schafer  coreyschafer@email.com   yoyo                  y     Yes
1      Dog       Doe       janedoe@email.com    Doe                  y     Yes
2    Smith     Smith     JohnSmith@email.com  Doeee  JohnDoe@email.com     Yes

In [91]:
df['boolean'].replace({'Yes':'True'}, inplace = True)

In [92]:
df

     first last_name               fullemail   last              email boolean
0  schafer   schafer  coreyschafer@email.com   yoyo                  y    True
1      Dog       Doe       janedoe@email.com    Doe                  y    True
2    Smith     Smith     JohnSmith@email.com  Doeee  JohnDoe@email.com    True

In [94]:
df['boolean'].map({'True' : 'Yes'})

0    Yes
1    Yes
2    Yes
Name: boolean, dtype: object

In [95]:
df

     first last_name               fullemail   last              email boolean
0  schafer   schafer  coreyschafer@email.com   yoyo                  y    True
1      Dog       Doe       janedoe@email.com    Doe                  y    True
2    Smith     Smith     JohnSmith@email.com  Doeee  JohnDoe@email.com    True